name: Playbook Houdini Plugin CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SECRET_NAME: ${{ secrets.SECRET_NAME }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r houdini/python3.11libs/playbook_utils/requirements.txt

    - name: Run tests
      run: |
        cd houdini/python3.11libs/playbook_utils
        python -m pytest test_auth.py

    # Add more steps as needed, such as:
    # - Building the plugin
    # - Running more tests
    # - Creating releases
    # - Deploying to production
